### ISSUE TITLE
Unexpected behavior of the "include_top" argument

### ISSUE THREAD

**Issue by nixingyang** [larq/zoo#101]
### Describe the bug

For backbone models defined in "densenet.py" and "resnet_e.py", current implementation adds the relu activation layer only if the "include_top" argument is True.
```plaintext
https://github.com/larq/zoo/blob/v0.5.0/larq_zoo/densenet.py#L70-L74
https://github.com/larq/zoo/blob/v0.5.0/larq_zoo/resnet_e.py#L71-L75
```
This is different from the behavior of keras-applications.
```plaintext
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/densenet.py#L228-L229
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/inception_resnet_v2.py#L329-L330
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/inception_v3.py#L360-L361
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/mobilenet_v2.py#L384-L386
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/mobilenet.py#L244-L256
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/nasnet.py#L242-L243
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/resnet_common.py#L381-L382
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/resnet50.py#L257-L258
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/vgg16.py#L177-L180
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/vgg19.py#L189-L192
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/xception.py#L270-L271
```

### To Reproduce

Just check the source code :-)

### Expected behavior

The relu activation layer should be added outside the if/else statement.

### Environment
TensorFlow version: 1.15.0
Larq version: 0.8.4
Larq-Zoo version: 0.5.0

**Comment by AdamHillier** [comment]
Hey @nixingyang, thank you for your interest in Larq and Larq Zoo!

It does indeed look like our behaviour in this regard differs to that of `keras-applications`. @lgeiger / @koenhelwegen thoughts on moving the activation out of the if statement?

**Comment by koenhelwegen** [comment]
I see no reason to deviate from keras here, so would be happy to change it (but I think @lgeiger knows these models best, perhaps he knows why it's currently like this).

**Comment by lgeiger** [comment]
I agree, we should do the same as Keras.

If I recall correctly the reasoning behind not including relu if `inlcude_top=False` was that if you want to add more binary layers after the network it might not be desired to have the relu included. This is not a problem for full precision networks as there should always be non-linearity between layers.
