### ISSUE TITLE
Unexpected behavior of the "preprocess_input" function

### ISSUE THREAD

**Issue by nixingyang** [larq/zoo#102]
### Describe the bug

The "larq_zoo.data.preprocess_input" function is define in the following sections:
```plaintext
https://github.com/larq/zoo/blob/v0.5.0/larq_zoo/data.py#L18-L32
https://github.com/larq/zoo/blob/v0.5.0/larq_zoo/data.py#L238-L253
```
If the argument "image" is a numpy array, the data flow would be CPU -> GPU -> CPU. And then feeding the data to GPU for trainings.
This slows down the trainings significantly if one uses a data generator of numpy arrays.

### To Reproduce

Just check the source code :-)

### Expected behavior

Actually, you don't need to implement this function from scratch.
The "keras_applications.imagenet_utils.preprocess_input" would work just fine with the "mode" argument set to "torch".
```plaintext
https://github.com/keras-team/keras-applications/blob/1.0.8/keras_applications/imagenet_utils.py#L157
```

### Environment
TensorFlow version: 1.15.0
Larq version: 0.8.4
Larq-Zoo version: 0.5.0

**Comment by koenhelwegen** [comment]
Hi, thanks for pointing this out. In our own usage we never feed in numpy arrays, but feel free to reopen or make a PR if this is a concern for you.
