### ISSUE TITLE
Support TensorFlow 2.2

### ISSUE THREAD

**Issue by lgeiger** [larq/zoo#133]
### Describe the bug
TensorFlow 2.2  doesn't rely on the `keras_applications` pypi package anymore. We should either change to import it from the TensorFlow version, or explicitely include `keras_applications` as a dependency.

### To Reproduce
Install larq zoo on a fresh Python env and try to import a model:
```
  File "/Users/runner/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/larq_zoo/core/utils.py", line 8, in <module>
    from keras_applications.imagenet_utils import _obtain_input_shape
ModuleNotFoundError: No module named 'keras_applications'
```

### Environment

TensorFlow version: 2.2.0rc0
Larq version: 0.9.1
Larq-Zoo version: 1.0.0b3

**Comment by leonoverweel** [comment]
From the [release notes](https://github.com/tensorflow/tensorflow/releases)

> In `tf.keras.applications` the name of the "top" layer has been standardized to "predictions". This is only a problem if your code relies on the exact name of the layer.

Should we rename our `include_top` params to `include_predictions` to match this?

**Comment by lgeiger** [comment]
> Should we rename our include_top params to include_predictions to match this?


I think they only changed the layer names and not the keyword arguments: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/vgg16.py#L46

**Comment by leonoverweel** [comment]
Ah cool. I guess when we add proper layer naming then we can follow their new standard.
