### ISSUE TITLE
No 'sota' module

### ISSUE THREAD

**Issue by vinayprabhu** [larq/zoo#160]
### Describe the bug
`ModuleNotFoundError: No module named 'larq_zoo.sota'`

### To Reproduce
`!pip install larq-zoo
from larq_zoo.sota.quicknet import QuickNet`

### Expected behavior

Should have downloaded the QuickNet architecture.

### Environment

TensorFlow version: 1.15.2
Larq version: 0.9.4
Larq-Zoo version: 0.5.0

`import larq_zoo as lq
dir(lq)` 
results in:
`['BiRealNet',
 'BinaryAlexNet',
 'BinaryDenseNet28',
 'BinaryDenseNet37',
 'BinaryDenseNet37Dilated',
 'BinaryDenseNet45',
 'BinaryResNetE18',
 'DoReFaNet',
 'XNORNet',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'binarynet',
 'birealnet',
 'data',
 'decode_predictions',
 'densenet',
 'dorefanet',
 'preprocess_input',
 'resnet_e',
 'utils',
 'xnornet']`

**Comment by lgeiger** [comment]
We will release the next stable version of larq zoo very soon.

For now you need to install the pre-release as descibed in https://docs.larq.dev/zoo/#installation

Running
```
pip install larq-zoo --pre
```
Should give you version `1.0.0b4` which includes the `sota` module.

**Comment by lgeiger** [comment]
We just release `v1.0.0`, so `pip install larq-zoo` will now give you the latest stable version which includes the `sota` module.
