### ISSUE TITLE
Speech Models

### ISSUE THREAD

**Issue by powderluv** [larq/zoo#173]
Binarized Speech models would be a awesome addition to the zoo if you support it.  Please add them if you have any canonical models.

**Comment by rnusselder** [comment]
Hi @powderluv, it's great to see that you're interested in Larq! We have actually been training BNNs for speech tasks. We currently don't plan to add them to Larq Zoo, but I'd love to chat with you to see if we can help you. You can reach me here: roeland@plumerai.com.

**Comment by powderluv** [comment]
hey @rnusselder - Thanks for the quick response. Im just kicking around what is available right now. I can reach out once we actually start using it so we don't waste your time :) 

Thanks
