### ISSUE TITLE
Help, no logs are printed!

### ISSUE THREAD

**Issue by HamLaertes** [larq/zoo#257]
### Describe the bug
When I run `lqz TrainR2BStrongBaseline`, after the training process has started, no logs are printed.
To ensure that the training process starts correctly, I have written a Callback:
```
class PrintCheckCallback(tf.keras.callbacks.Callback): 
    def on_train_batch_begin(self, batch, logs=None): 
        print("training on batch: {:4d}".format(batch))
```
And this callback is able to print the current batch index correcly, so I can be sure that the training process had started.
I am thinking whether this is a bug or there is no printed logs indeed?

### To Reproduce

I clone the code and use `pip install -e .` to generate the module locally.

### Expected behavior

I wish to monitor the training process, so it's necessary to have training logs printed.

### Environment

TensorFlow version:  2.3.1
Larq version:  0.10.2
Larq-Zoo version: 2.0.1 (build locally)

**Comment by AdamHillier** [comment]
Hey, thanks for your interest in Larq Zoo :)

By default our training code prints logging information at the end of each epoch, and when training on ImageNet (especially with a single GPU) the epochs can take quite a while. You can enable per-batch logging with:

```
lqz TrainR2BStrongBaseline --stage_0.use_progress_bar --stage_1.use_progress_bar
```

I hope that helps.

**Comment by HamLaertes** [comment]
> Hey, thanks for your interest in Larq Zoo :)
> 
> By default our training code prints logging information at the end of each epoch, and when training on ImageNet (especially with a single GPU) the epochs can take quite a while. You can enable per-batch logging with:
> 
> ```
> lqz TrainR2BStrongBaseline --stage_0.use_progress_bar --stage_1.use_progress_bar
> ```
> 
> I hope that helps.

Oh, this is exactly what I want.
Thank u very much.
