### ISSUE TITLE
Add training code and guides of the pretrianed models

### ISSUE THREAD

**Issue by JM-IP** [larq/zoo#48]
To fully leverage the existing methods, we should need the training process of the pre-trained models.

**Comment by lgeiger** [comment]
> To fully leverage the existing methods, we should need the training process of the pre-trained models.

@JM-IP I agree, reproducible training process is very important to us as well. Have you checked out the training code [here](https://github.com/larq/zoo/blob/master/larq_zoo/train.py) and [here](https://github.com/larq/zoo/blob/master/larq_zoo/birealnet.py#L7-L96)?

I also added some documentation on how to reproduce model training from scratch: https://larq.dev/models/#training-models-from-scratch

Feel free to reopen this issue if you have more questions or if you need help with something specific.
