### ISSUE TITLE
SOTA pretrained models in larq_zoo

### ISSUE THREAD

**Issue by hukim0707** [larq/zoo#99]
Hi,
I really appreciate your framework larq and the pretrained weights in larq_zoo.
Currently, there are 9 pretrained weights for the selected models including AlexNet and DenseNet.
Is there any plan to expand the number of uploaded pretrained weights for other BNN models?

I recently found SOTA BNN reference which is called MeliusNet
https://arxiv.org/abs/2001.05936

Thank you.

**Comment by lgeiger** [comment]
Thanks for taking a look at `larq` and `larq/zoo`. 

> Is there any plan to expand the number of uploaded pretrained weights for other BNN models?

Yes, we plan to add more models in the future. `larq/zoo` has been quiet for some time, but we definitely plan to expand the available models in the near future.
Currently `larq/zoo` only includes models from paper reproductions, though we are exploring possibilities to expand the scope and add some SOTA models. We might write a proposal for this in the coming weeks, it would be good to get some feedback from the community on this as well then.

> I recently found SOTA BNN reference which is called MeliusNet

We currently don't have plans to add MeliusNet to the model zoo, though we would be very happy to accept PRs for adding it. If you would be interested in contributing the model to `larq/zoo` we would be very happy to help.

**Comment by hukim0707** [comment]
Thanks a lot!
